theme: jekyll-theme-midnight
title: Bioinformatics using metabarcoding data practical
description: Bioinformatics practical for Masters students Imperial College London students using data from soil metabarcoding data Silwood Park EFN points
